// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_uPiM3mXBJH4poJIM7huxJxPQ8rAQPWI',
    appId: '1:627448491131:web:be4ac5e1598513792846de',
    messagingSenderId: '627448491131',
    projectId: 'lisa-it-b1e75',
    authDomain: 'lisa-it-b1e75.firebaseapp.com',
    storageBucket: 'lisa-it-b1e75.firebasestorage.app',
    measurementId: 'G-CY3X6BK46S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAMlpCgEQIoB6Evu-G8WsiEzTqEhJN5zE',
    appId: '1:627448491131:android:0a4c0ac5054102692846de',
    messagingSenderId: '627448491131',
    projectId: 'lisa-it-b1e75',
    storageBucket: 'lisa-it-b1e75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTASM-eg4-GYxWgLQ2a8xXHuHMdYy3fNU',
    appId: '1:627448491131:ios:1195ac998e661af42846de',
    messagingSenderId: '627448491131',
    projectId: 'lisa-it-b1e75',
    storageBucket: 'lisa-it-b1e75.firebasestorage.app',
    iosBundleId: 'com.example.lisait',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTASM-eg4-GYxWgLQ2a8xXHuHMdYy3fNU',
    appId: '1:627448491131:ios:1195ac998e661af42846de',
    messagingSenderId: '627448491131',
    projectId: 'lisa-it-b1e75',
    storageBucket: 'lisa-it-b1e75.firebasestorage.app',
    iosBundleId: 'com.example.lisait',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_uPiM3mXBJH4poJIM7huxJxPQ8rAQPWI',
    appId: '1:627448491131:web:13101dea2b3a85162846de',
    messagingSenderId: '627448491131',
    projectId: 'lisa-it-b1e75',
    authDomain: 'lisa-it-b1e75.firebaseapp.com',
    storageBucket: 'lisa-it-b1e75.firebasestorage.app',
    measurementId: 'G-F6TM9RZ895',
  );
}
